apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracing-example.fullname" . }}
  labels:
{{ include "tracing-example.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 18080
      targetPort: 18080 
      protocol: TCP
      name: frontend
  selector:
    app.kubernetes.io/name: {{ include "tracing-example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
